# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy application code
COPY . ./

# Expose stdio use, no ports needed
# Set default command
CMD ["node", "index.mjs"]
